### ISSUE TITLE
I use it and send data to the client. The client only has props and didn't do the corresponding actions. How to solve it?

### ISSUE THREAD

**Issue by Xcker8** [Squizzor/SquizzorObjectAttacher#2]
I use it and send data to the client. The client only has props and didn't do the corresponding actions. How to solve it?
    'fishing': {
        objectName: 'prop_fishing_rod_01',
        boneId: 60309,
        position: { x: 0, y: 0, z: 0, },
        rotation: { x: 0, y: 0, z: 0 },
        enterAnimation: { dict: 'amb@world_human_stand_fishing@idle_a', name: 'idle_c', flag: 49, durationMs: 25000 },
        exitAnimation: { dict: '', name: '', flag: 49, durationMs: 0 }
    },

server:
player.EmitLocked("objectAttacher:attachObject", "fishing");

**Comment by Squizzor** [comment]
Hello Xcker8,
attaching an object animated from server side was indeed not completely implemented yet. I just changed that and also included the fishing rod to the objects array.

You can now attach an object and let the attacher also play the corresponding animation. You have to use the "objectAttacher:attachObjectAnimated" term for that.
Example code:
player.Emit("objectAttacher:attachObjectAnimated", "fishing-rod", true);

The last parameter (true) defines whether the object should be detached after the animation finishes (only when there is a duration set for the animations, otherwise the animation would loop infinitely). Also take a look at the updated project description at "Attach or detach an object".

You might also want to change the duration for the fishing rod animation to your desire again (its 0 at the moment).

**Comment by Xcker8** [comment]
Why am I not working?

**Comment by Xcker8** [comment]
Personal suggestion, you can add a character freeze option, the character cannot move while fishing, and you can move freely when the time is over

**Comment by Squizzor** [comment]
You can freeze the player when using 15 as animation flag. This will disable player control.
I also changed it for the fishing rod to 15 in my branch.
See https://natives.altv.mp/#/0xEA47FE3719165B94 for further information on the animation flags.
Please close the issue when things are working for you ;)

**Comment by Xcker8** [comment]
Can you leave your discord?

**Comment by Squizzor** [comment]
Squizzor#8457
